### ISSUE TITLE
Depending on Meteor causes issues when creating a package

### ISSUE THREAD

**Issue by arggh** [FGM/filog#13]
If I want to encapsulate FiLogger to a reusable Atmosphere/Meteor package, I get this when I try to import anything:

```
W20161119-17:35:55.303(2)? (STDERR) ReferenceError: Meteor is not defined
W20161119-17:35:55.303(2)? (STDERR)     at Object.<anonymous> (/dev/packages/logger/.npm/package/node_modules/filog/lib/index.js:64:20)
W20161119-17:35:55.303(2)? (STDERR)     at Module._compile (module.js:409:26)
W20161119-17:35:55.304(2)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20161119-17:35:55.304(2)? (STDERR)     at Module.load (module.js:343:32)
W20161119-17:35:55.304(2)? (STDERR)     at Function.Module._load (module.js:300:12)
W20161119-17:35:55.305(2)? (STDERR)     at Module.require (module.js:353:17)
W20161119-17:35:55.305(2)? (STDERR)     at require (internal/module.js:12:17)
W20161119-17:35:55.306(2)? (STDERR)     at npmRequire (/dev/app/.meteor/local/build/programs/server/npm-require.js:133:10)
W20161119-17:35:55.306(2)? (STDERR)     at Module.Mp.useNode (packages/modules-runtime.js:493:20)
W20161119-17:35:55.306(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:180:20)
```

There is a `Meteor.isServer` check in `/lib/index.js` that's causing this.

**Comment by FGM** [comment]
The way I see it, this is not an issue: we created Filog as a NPM module to avoid depending on the Atmosphere system like we did for prior packages, as the (admittedly ever-mutating) MDG strategy seems to be clearly to use NPM for everything except Meteor core for a few more releases.

So if you find a mostly compatible way to address this issue to create an Atmosphere package and submit a PR, it could be merged, otherwise I'm inclined to mark this as "wontfix".

**Comment by arggh** [comment]
The point was not to avoid depending on Atmosphere, but to allow the usage of FiLog **in** Meteor packages (local or published to Atmosphere), not just Meteor apps.

Even though Meteor has gone the way it has, I believe local Meteor packages still have a lot of valid use cases.

**Example scenario:**

- I have a custom written job-queue-package (Meteor local package), that defines some available job tasks and has a processor for them as well. It sends emails, does some batch jobs etc...

- I would like to log the possible events taking place in the job queue, like a failed emailing process.

- I cannot use FiLog, because when I try to include it in my package, it assumes there is a global Meteor object around (and Meteor packages by design cannot access globals from the app)

I've never created NPM Packages for Meteor, but one would think there is a way to handle things so that this is not a problem.

**Comment by FGM** [comment]
I agree it makes some sense, but the way I see it, a Meteor package should not depend on FiLog or any other logging package for that matter, but accept an injected "logger" variable defaulting to the one provided by Meteor. Applications can then initialize the package by passing an instance of whichever logger they chose to bring in: as long as it follows the (admittedly undocumented, but still quite stable over time) of Meteor "Log", packages should work normally.

**Comment by arggh** [comment]
Thanks for helping me think this through, you're right. I'm so mingled currently in my self-inflicted jungle of packages and projects that I can't think straight..
