### ISSUE TITLE
"Cannot read property 'timestamp' of undefined" in MongodbSender.send

### ISSUE THREAD

**Issue by yched** [FGM/filog#20]
App works fine with filog 0.1.8. 

If upgraded to 0.1.10, we get :
```
TypeError: Cannot read property 'timestamp' of undefined
  at MongodbSender.send ([...app]/node_modules/filog/lib/Senders/MongodbSender.js:67:18)
```
on server startup

**Comment by FGM** [comment]
Duplicate of #18 : until 0.1.11 is released, use the git version from the v0.1.11 branch or the packaged release candidate available on #18.
