### ISSUE TITLE
Make syslog output more parseable

### ISSUE THREAD

**Issue by FGM** [FGM/filog#33]
Currently, the syslog messages being sent are just v8 inspection strings, as the result of `util.inspect(doc)`. 

See SyslogSender::send():

```javascript
    this.syslog.log(level, util.inspect(doc, this.formatOptions));
```

The reason for this is to ensure data can actually be serialized, and a more common format like JSON does not ensure serializability.

The envisioned strategy is to replace this by an exception-handling JSON stringifying in `SyslogSender::send()`:

* If `JSON.stringify` succeeds, then log the resulting JSON
* Else create a JSON containing: 
  * timestamp, priority
  * a "serialization error" information
  * possibly a message string, if available
  * the `util.inspect()` blob, as currently done

Allternative would be to have a user-space serialization library. Some of the envisioned ones are, in more or less decreasing relevance order:

* [Serialijse](https://www.npmjs.com/package/serialijse): supports classes, circular references
* (JBB)[https://github.com/wavesoft/jbb/wiki/Introduction-to-JBB]: efficient representation, supports object types, deduplicates information, might support circular references, but "JBB is quite slow on encoding" and produces a custom binary representation, which makes it a poor fit for a logging format which needs to be fast
* [Jahoo's Serialize Javascript](https://www.npmjs.com/package/serialize-javascript) (née express-state): handles functions, regexps, but not circular references
* [Seri](https://github.com/joonhocho/seri): handles Date types and custom classes, but not circular references
* [JSON2](https://github.com/douglascrockford/JSON-js): "There is no reason to use this file unless
fate compels you to support IE8"
* [Jsmix](https://github.com/khayll/jsmix): "This is a WIP project,"
* `JSON.stringify()` with a custom replacer, as documented at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify is just the underlying logic for these packages

In the longer run, this could mean using the Strategy pattern just like we did at the top level of the logging chain: the initial suggested solution is just a degenerate case of it.

**Comment by FGM** [comment]
In the suggested change, the serializer now is injectable and provides JSON as a default, now handling non-JSON-serializable data with a fallback to an error format including the util.inspect() blob. There is even a second-level safety fallback for unforeseen cases where util.inspect would fail too.

**Comment by FGM** [comment]
Changed wording and added server hostname per @yched review.

**Comment by yched** [comment]
Looks good on our test app :-)

**Comment by FGM** [comment]
Merged #34

**Comment by yched** [comment]
Was it merged ? I see nothing in the master history

**Comment by FGM** [comment]
On dirait que je n'aurais pas du utiliser l'UI de github 😥

Le mar. 11 avr. 2017 13:46, Yves Chedemois <notifications@github.com> a
écrit :
