### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by liu0fanyi** [FGM/filog#40]
I try to follow these: 

constructs a ClientLogger instance, passing it the strategy instance, like:
```
  let logger = new ClientLogger(new LeveledStrategy(
    new NullSender(),
    new ConsoleSender(),
    new MeteorClientHttpSender(Meteor.absoluteUrl('logger'))
  ));
```
adds processor instances to the logger instance, like:
```
  logger.processors.push(
    new BrowserProcessor(),
    new RoutingProcessor(),
    new MeteorUserProcessor(Meteor)
  );
```
is now able to log events, like:
```
  logger.warn("Some warning condition", { foo: "bar" });
```

## steps 

1. `meteor npm install filog --save`
2. `meteor add http`
3. `add up codes in client/main.js`

and `I can't find log anywhere...`

**Comment by FGM** [comment]
At this point, you only send the logs to Meteor, but when the server logger part receives the logs, it has no sender to do anything with them, so it just discards them. You also need to configurer a ServerLogger instance, probably with the Mongo sender to store them in the logs, or the Syslog sender to send them tou your syslog server.

**Comment by liu0fanyi** [comment]
@FGM Thank you for response , I will have a try

**Comment by FGM** [comment]
No more comment in over one month, assuming fixed.
