### ISSUE TITLE
[windows/error] meteor npm i filog --save

### ISSUE THREAD

**Issue by ontwikkelfabriek** [FGM/filog#41]
Running the command below in a windows 10 machine  results in error:

_meteor npm i filog --save_

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32
```

**Comment by FGM** [comment]
This error says modern-syslog is not supported on Windows (or as its author says, Windows doesn't support syslog), and Filog depends on it.

This would probably need one of three approaches:
- either creating a Windows port of modern-syslog, but see https://github.com/strongloop/modern-syslog/issues/20
- or unbundling the syslog dependency from Filog, maybe by declaring it as a peerDependency ? But then you would lose the most useful Sender class in the package, which makes the package a lot less useful IMO.
- or (simpler) you don't run your application natively on Windows but within a VM or container to have a Linux/UNIX kernel which support syslog natively.

Which do you prefer ?

**Comment by FGM** [comment]
No answer in over one month. Assuming lack of interest.
